# Generated by Django 5.1.4 on 2025-01-03 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='department_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='department_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='prescribed_medication_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='prescribed_medication_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='user_en',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='user_ru',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
