# Generated by Django 5.1.4 on 2025-01-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_site', '0002_doctor_department_en_doctor_department_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='user_en',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='user_ru',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status_en',
            field=models.CharField(choices=[('scheduled', 'Запланировано'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='scheduled', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status_ru',
            field=models.CharField(choices=[('scheduled', 'Запланировано'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='scheduled', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='blood_type_en',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='blood_type_ru',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
