# Generated by Django 5.1.4 on 2025-01-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_site', '0003_remove_patientprofile_user_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialty',
            new_name='speciality',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='specialty_en',
            new_name='speciality_en',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='specialty_ru',
            new_name='speciality_ru',
        ),
    ]
